### ISSUE TITLE
how to download?

### ISSUE THREAD

**Issue by DramaLvl1** [Baubo-LP/CityBuild-System#1]
I download it and it donsent work...
Pls add it for poggit

**Comment by Baubo-LP** [comment]
German: Was ist die Fehlermeldung? Du musst den ZIP Ordner entpacken und in dem entpackten Ordner ist das Plugin drin, welches du in deinen "plugins" Ordner hinein packst. Ich habe das Plugin falsch hochgeladen, weshalb das Plugin besser verpackt ist xD. 

---

English: What is the error message? You have to unpack the ZIP folder and in the unzipped folder is the plugin, which you put into your "plugins" folder. I uploaded the plugin incorrectly, which is why the plugin is packaged better xD.
